### ISSUE TITLE
[ACL] Contributors can't add polygon to granted layers

### ISSUE THREAD

**Issue by atalekar** [google/ground-android#1044]
A layer which collects polygon data, is only visible if the user is a manager on the project. Issue is restricted to the android app. I didn't even realize that acls were layer specific - as the UI doesn't allow that.

In our `one time` project `xxx field` layer which collects polygon is not visible as `contributor` but is visible as `manager` or `owner` in the list when you hit the `+` floating action button. Other layers which collect point info are visible to all.

**Comment by gino-m** [comment]
Hi @atalekar When you say visible, I assume you mean they don't appear in the list when _adding_ a feature, but features added or imported are visible on the map?

> A layer which collects polygon data, is only visible if the user is a manager on the project. Issue is restricted to the android app. I didn't even realize that acls were layer specific - as the UI doesn't allow that.

You should be able to allow contributors to add polygons to a layer through the "Customize layer" dialog in the web app. For example:

![image](https://user-images.githubusercontent.com/228050/142081561-e7cb0e92-2ddd-4f77-8cdc-ae09c84011ec.png)

Once you do that, you'll need to sign out and back into the app again since we don't yet react to remote project changes automatically.

Please let me know if this solves it!



> 
> In our `one time` project `xxx field` layer which collects polygon is not visible as `contributor` but is visible as `manager` or `owner` in the list when you hit the `+` floating action button. Other layers which collect point info are visible to all.

**Comment by gino-m** [comment]
@atalekar I was able to reproduce this on my test project. Looking further, this is likely related to #1035.
