### ISSUE TITLE
[Add polygon] Nothing changes when first vertex is added

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1056]
There is no indication that a vertex was added when Add Point is first clicked. 

@shobhitagarwal1612 Could you PTAL when you have a sec?

**Comment by shobhitagarwal1612** [comment]
A couple of ideas:

1. Setting the default text of button as "Start" which changes to "Add point" after clicking it?

2. Showing selected vertex counter at the top

3. Adding a marker on the start position which gets removed after completing the polygon drawing. 

@gino-m Thoughts?

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612 I'd be in favor of option #3, since it's consistent with the rest of the flow.

We will probably need to add ephemeral round markers (markers that are shown only in add/edit polygon) to the map anyway for two reasons: 1) Maps SDK only shows the round markers as end caps on the poly line while drawing, not on all vertices as expected and 2) the edit flow will need round markers on all vertices as affordances for selecting a vertex to edit.

Wdyt?

**Comment by shobhitagarwal1612** [comment]
That sounds good to me. Since we need handle rendering of transient polygons separately, i feel this should be the order of changes:

1. Separate the rendering of saved polygons and temporary polygons.
2. Create feature from the temporary polygon at the end rather than from the beginning to prevent recreation of feature on every vertex update. Also decouple selected project and layer from PolygomDrawingView, if possible.
3. Add logic to add a marker for each temporary vertex (except the last one).

Wdyt?

**Comment by gino-m** [comment]
Sounds reasonable. To achieve (1), would we decouple `Feature` from the maps interface, and pass points and polygons instead?
