### ISSUE TITLE
[Sync status] DELETE mutations are not shown in sync status UI

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1059]
Found by @rachaprince

**Comment by scolsen** [comment]
I believe this happens because we use the feature/observation ID as a foreign key on mutations and cascade deletions, so as soon as the feature deletion is successful, the corresponding mutations for the feature are also removed from the DB. 

You can also see this behavior in the sync status list by deleting any entity you create--the sync history for that entity will also disappear from the UI.
