### ISSUE TITLE
[UX] Join Project list shows already joined projects

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1066]
**Describe the bug**
Join Project list includes already joined projects.

**To Reproduce**
1. Go to Join Project in drawer and select any project
2. After the project is loaded, goto the Join Project again
3. The previously selected project can still be selected.

**Expected behaviour**
Selecting the already loaded project should not be allowed. It can be achieved in the following ways:
 1. Hiding the loaded projects
 2. Adding a "saved" label and making the item unclickable.
 3. Adding a project management screen and handling this along with that.

**Comment by gino-m** [comment]
Thanks for filing this @shobhitagarwal1612. You've hit on a broader design issue we have; if we really want to allow multiple projects to be used offline, we should update the UI to an "Add/remove projects from device" paradigm rather than a "Join a project" and have them accumulate ad infinitum in the side bar. Let's discuss a bit before making any changes here.

**Comment by shobhitagarwal1612** [comment]
@scolsen Can we close this in favour of new welcome screen?
