### ISSUE TITLE
"Error loading config from remote server" even when they had good network connectivity

### ISSUE THREAD

**Issue by atalekar** [google/ground-android#1072]
One user is getting a toast message and is unable to launch ground even when they had network access
```
Ground:
Error loading config from remote server.
```
Attaching screenshot on the internal bug

**Comment by shobhitagarwal1612** [comment]
It happens to me when I use a DNS blocker on my device which blocks all calls to firebase APIs. Try disabling it before opening the app.

**Comment by gino-m** [comment]
@shobhitagarwal1612, I was able to reproduce this on the emulator as follows:

1. Sign in and join a project
2. Kill the app
3. Enable Airplane Mode
4. Try to open the app, receive error message
5. Disable Airplane Mode
6. Open app, same error message is displayed.

We would expect the app to be able open normally in step #4 and #6. Possible due to #1026?
