### ISSUE TITLE
[Data collection] New data collection flow

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1146]
@ngosue Please to mocks or a public link here when ready!

@jsunde This issue is intended to only include the basic "answer a question" (text) and "take a picture" data collection tasks. Other tasks can be split among the team.

**Comment by JSunde** [comment]
I believe the data collection flow for all of the following P0 task types has been completed.

P0 Task Types:
- [x] Take Photo
- [x] Answer a Question
    -  [x] Text
    -  [x] Select one (radio button)
    -  [x] Select multiple (checkbox)
    
I think the only thing I can think of that is remaining before we can close this issue is the summary screen at the end of the data collection flow. Currently the job is completed when the user hits "Continue" on the final task in the job, but I believe we want to show a summary screen with a list of the tasks that the user responded to before the job is completed.

@gino-m can you remind me if that screen is in scope for the current prototype? And if so do you think it should be included in this issue or a follow up one?

**Comment by gino-m** [comment]
> I believe the data collection flow for all of the following P0 task types has been completed.
> 
> P0 Task Types:
> 
> * [x]  Take Photo
> * [x]  Answer a Question
>   
>   * [x]  Text
>   * [x]  Select one (radio button)
>   * [x]  Select multiple (checkbox)
> 
> I think the only thing I can think of that is remaining before we can close this issue is the summary screen at the end of the data collection flow. Currently the job is completed when the user hits "Continue" on the final task in the job, but I believe we want to show a summary screen with a list of the tasks that the user responded to before the job is completed.
> 
> @gino-m can you remind me if that screen is in scope for the current prototype? And if so do you think it should be included in this issue or a follow up one?

I can't find the mocks for that screen, and it's not essential for the e2e flow to work. I think we can close the data collection flow and file that as a separate P2 FR.
