### ISSUE TITLE
[Map] Show job cards at bottom of map

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1153]
- Each card represents one LOI.
- Cards show: Job name, LOI name and ID (if present), Completion status, "START" affordance to collect data
- If identical LOIs (e.g., same coordinates) exist in multiple jobs, one card is shown for each
- Swiping through cards sets focus to LOI 
- List updates after map settles after panning/zooming

@ngosue Please paste mocks once ready

**Comment by shobhitagarwal1612** [comment]
I've started working on this feature. I'm planning to implement this in multiple phases rather than a very big PR:

### 1. Basic implementation of cards for each LOI. 

* Adding a recycler view to the MapContainerFragment 
* Showing a card item for all LOIs in the active survey.
* On switching the survey, the cards should also get updated.
* Only basic information (jobName, loiCaption, etc.) would be shown

### 2. Filtering cards based on map viewport

* Filter the cards based on current LatLng bounds
* List should auto-update on panning/zooming in addition to switching survey

### 3. Add focus to LOI map pin when swiping the card list

* Add a focus property to view holder and update UX of selected card
* Get LOI id from the viewholder and update the UX of drawn geometry

### 4. Integrate with data collection flow

* Add listener to "Start" button
* Change button text to "complete" if the target is complete
* Add completion status to each card

**Comment by shobhitagarwal1612** [comment]
Confirmed UX behaviours (@ngosue):

1. Cards should get auto-selected on swiping. In addition to that, clicking should also select the card.
2. Highlight the selected card (for prototyping, add some border color)
3. Also focus the LOI when selecting a card
4. GPS button should be anchored to the card list (so drop it to the bottom when empty)
5. Map type should be on top right corner, below search bar (similar to gmaps)

**Comment by shobhitagarwal1612** [comment]
Cards are current added directly to the `MapContainerFragment`. This prevents unit testing of the UI since it expects `GoogleMapFragment` which isn't available in unit tests. Therefore, in order to improve test coverage, we might have to either create a custom ui or remove dependency on GoogleMapFragment in unit tests

**Comment by shobhitagarwal1612** [comment]
I was referring to creating a view container which will only contain the recycler view.
