### ISSUE TITLE
[DataCollectionFlow] List tasks are not properly aligned

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1450]
The select one and select multiple Data Collection Tasks currently have the list items centered between the header and the continue button, but they should be aligned directly below the header.

**Comment by gino-m** [comment]
@JSunde Let's use the custom "Feature" field in project instead of labels for feature, ie

![image](https://user-images.githubusercontent.com/228050/215216714-7de6799b-6a7a-493f-ba8f-85c4b222a540.png)

And not:

![image](https://user-images.githubusercontent.com/228050/215216736-79e1f249-0810-423d-9fdc-0656e0a8ad30.png)

**Comment by JSunde** [comment]
SG
