### ISSUE TITLE
[Regression] Points are not getting highlighted when selecting bottom cards

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1457]

**Comment by gino-m** [comment]
@shobhitagarwal1612 Could you PTAL this one?

**Comment by shobhitagarwal1612** [comment]
`onBeforeClusterItemRendered` in `FeatureClusterRenderer` doesn't get called after updating the selected LOI. @scolsen fyi

**Comment by scolsen** [comment]
Started looking into this today. There are a few problems that make this less straightforward than I would have hoped:

1. The easy bit is that there is a separate function we need to override on Cluster Item Update.
2. SetActiveLOI is being called with null ID values when the user zooms in, even if a valid card is still active.
3. The Cluster uses point based identity to update managed feature items instead of reference id. This seems to induce conflicts occasionally
