### ISSUE TITLE
App crashes after opening job with different tasks

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1608]
**Describe the bug**
App crashes if a task of different type is opened

**To Reproduce**
1. Open a job containing "text" task. 
2. Finish all responses and click continue
3. Open another job containing "number" task
4. App crashes

**Expected behavior**
Correct tasks should get loaded

**Actual behavior**
App crashes as the fragment tries to cast `TextTaskViewModel` to `NumberTaskViewModel`

The issue seems to be that DataCollectionViewModel doesn't reset the state after data collection is completed or canceled.

@JSunde This seems related to the recent addition of persisting VMs across config changes. Could please take a look and fix this?

**Comment by JSunde** [comment]
Oh hmm, I think this might be because we use activityViewModels to share the DataCollectionViewModel between the DataCollectionFragment and the child task fragments. I think the problem then is that this DataCollectionViewModel is shared from one instance of the DataCollectionFragment to another.

Any ideas how we could share the DataCollectionViewModel between the DataCollectionFragment and its child fragments, without sharing that same DataCollectionViewModel instance from one DataCollectionFragment to the next?

@shobhitagarwal1612 @scolsen @gino-m

**Comment by shobhitagarwal1612** [comment]
Is it possible to dispose off the VM instance after the collection is complete or canceled?

**Comment by JSunde** [comment]
I'm wondering if we might want to use navGraphViewModels? It sounds like that might address this particular issue where there may only be one activity for the app, but you want a view model shared between some subset of fragments.
https://medium.com/android-dev-hacks/exploring-scoped-viewmodels-79f70c86f569

**Comment by JSunde** [comment]
@scolsen @shobhitagarwal1612 do you have thoughts on how I could accomplish this with the nav graph? I'm not that familiar and I tried wrapping the data collection fragment in another `navigation` so that I could try to scope the view model to that sub nav graph, but I can't figure out how to launch the data collection fragment when it's inside a sub nav graph.

**Comment by scolsen** [comment]
Not super familiar with sub nav graphs, but I think we can figure this out, let's chat about it.
