### ISSUE TITLE
Data collection progress indicator appears over tasks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1975]
Green horizontal line appears across screen.

Trying on Pixel 4 API 32, photo was not first task in job.

![image](https://github.com/google/ground-android/assets/228050/1cefdfaf-c5be-4fd5-863d-14c6928912ca)

**Comment by shobhitagarwal1612** [comment]
While testing it today, I found that the "progress indicator" is missing as well.

**Comment by gino-m** [comment]
@justinktang

**Comment by gino-m** [comment]
Confirmed, the progress bar is missing in all tasks tested.

<img width="260" alt="image" src="https://github.com/google/ground-android/assets/228050/aba75b81-1269-4119-b4f7-8b584dab57ae">

Expected:

![image](https://github.com/google/ground-android/assets/228050/61bc6e1b-1ccb-4caa-8af6-bc047fd10304)

**Comment by gino-m** [comment]
Hi @justinkimtang, just noticed that this is still happening on `master`:

<img width="408" alt="image" src="https://github.com/google/ground-android/assets/228050/8bbf80aa-49cc-4c8b-b5de-d09f75f541dd">

Not sure if it matters, but in this case the photo task was the second task in the job. PTAL?

**Comment by jcqli** [comment]
@shobhitagarwal1612 Are you able to take this on for this iteration?

**Comment by sufyanAbbasi** [comment]
Repro: open the keyboard for a text based task then press "Previous" and the progress bar will get stuck in the middle of the screen:

<img width="348" alt="Screenshot 2024-02-29 at 4 22 36 PM" src="https://github.com/google/ground-android/assets/12646706/47c1f3c3-4fff-4d80-85b2-5cf1c1fc8f27">

**Comment by sufyanAbbasi** [comment]
Hypothesis: here in `DataCollectionFragment`, in `OnPageChangeCallback()` we attempt to reposition the progress bar based on the current position of the `action_buttons`.

However, when the keyboard is open, the position of the action buttons are shifted, so when we move back, the instantaneous position of the `action_buttons` is far higher than it should be, thereby setting the progress bar in the wrong place.

```
          val buttonContainer = view.findViewById<View>(R.id.action_buttons) ?: return
          val anchorLocation = IntArray(2)
          buttonContainer.getLocationInWindow(anchorLocation)
          val guidelineTop =
            anchorLocation[1] - buttonContainer.rootWindowInsets.systemWindowInsetTop
          guideline.setGuidelineBegin(guidelineTop)
```

Two proposals:
  - Somehow make the `progress_bar_guideline` to dynamically constrain to the `action_buttons` (difficult because they are defined in different fragments), don't dynamically calculate it.
  - Delay the calculation of the action button position to after they settle.
  - Move the progress bar to a static location.

**Comment by sufyanAbbasi** [comment]
Went with option 2 for the simplest approach.
