### ISSUE TITLE
Imported polygons not appearing when zooming into cluster

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2092]
@shobhitagarwal1612 PTAL?

Cluster markers are shown when zoomed out, polygons not shown when zoomed in.

**Comment by shobhitagarwal1612** [comment]
I wasn't able to reproduce the bug, but I have a theory which might be causing some confusion to the users:

1. User opens the app and zooms in to a cluster and enters data collection mode (current location is off)
2. First task is "Capture location" which auto-enables the current location
3. User submits the data and moves back to the previous home screen
4. Since the location is enabled, map moves the camera to current location which doesn't contain any LOI.

**Comment by scolsen** [comment]
I was seeing this on survey w/ ID `szxIGR3u68e8Zmq9vhmn`

**Comment by scolsen** [comment]
I can confirm this issue persists for the survey with the ID I listed. Interestingly, though, another survey, using the same geojson data, does _not_ have this issue.

**Comment by scolsen** [comment]
After digging into this further, I think this is actually a web bug. The android app is doing the right thing. It turns out the polygons in this survey all have a color of 0 and vertex style of none:

```
style=Style(color=0, vertexStyle=NONE)
```

Contrast this with the import of the same data I performed today, which set all the polygons to have the following styling:

```
style=Style(color=-820190, vertexStyle=NONE)
```

The issue is that the JSON import for this survey, for whatever reason didn't set colors correctly.

**Comment by scolsen** [comment]
Another key diff: the job in which this is happening has *no default style* value (empty object). This might be the root cause.

**Comment by scolsen** [comment]
Sure enough: `Invalid or missing color  in job PgOhqF1Ewm4LFP8fLMqW`

When this happens, we return `0`, which Android is rendering as an invisible color because Polygons use ARGB. 0 is  completely transparent.
