### ISSUE TITLE
Access to offline imagery doesn't authenticate using user's credentials

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2115]
This requires the bucket to allow public access. To prevent misuse, we should authenticate using the current user's credentials. Proposed design with @sufyanAbbasi: 

- [ ] Move data from GCS into Firebase Storage
- [ ] Replace custom `tileSources` config in survey document with "configuration by convention": 
  - [ ] Look for tiles under `/offline-imagery/default/{z}/{x}/{y}.tif`, where `{z}` is the zoom level at which hi-res tilesets are sliced. The hi-res tilesets have tiles starting at zoom level _z_
  - [ ] Assume the overview image will be in `/offline-imagery/default/{z}/overview.tif`. The overview will have zoom levels  0.._z_-1. This will replace the current hard-coded `world-masked.tif`.
  - [ ] Read zoom level extents of `overviewtiff` and hi-res imagery directly from GeoTIFFs
- [ ] Update `MogClient` to get `InputStream` from Firebase SDK instead of `UrlInputStream`. This should handle auth for us.
- [ ] Update Firebase Storage Rules to only allow access to `/offline-imagery` if user is in passlist (https://github.com/google/ground-platform/issues/1373)

**Comment by gino-m** [comment]
We should also address or at least consider photo authentication when addressing this issue.

**Comment by sufyanAbbasi** [comment]
Reopening because there are a few changes to make here:

1. Don't pull tileSource from the survey record. Instead, assume a default path to `offline-imagery/default` or some other configuration in `Config.kt`.
2. Always show the "download offline imagery" button on the nav menu
3. Attempt to pull from the default location, fail gracefully otherwise.
