### ISSUE TITLE
[Code health] MutationRepository Cleanup

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#2119]
I think our overall approach and design will be simplified if we dumb down the logic the `MutationRepository` offers and offload some processing into methods defined directly on our mutation value types.

**Comment by gino-m** [comment]
Working on #2867 now; exposing more fine-grained logic from `MutationRepository` has a few benefits:

* It makes the workers more readable, since a named handle for these methods are available rather than needing to depend on the details of how states are represented internally.
* It makes code less fragile by keeping the moving the "how" states are represented closer to the data rather than the business logic.

Closing for now, @scolsen please reopen if you have strong feelings about this!
