### ISSUE TITLE
[Add LOI task] Allow user to name LOIs when adding

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2267]
![image](https://github.com/google/ground-android/assets/228050/8463fcbe-4160-4cba-8917-28af48422158)

@rawbzz FYI

**Comment by gino-m** [comment]
Requested by @lecrabe. Added to the next milestone after field testing.

**Comment by sufyanAbbasi** [comment]
Had a chance to discuss the solution with @shobhitagarwal1612, who gave me some implementation details to consider.  I found that the code complexity increases substantially when the dialog is to be triggered inside of the `*TaskFragment` (i.e. capture location, point, and polygon tasks), in between when the location is captured but before hitting next while the user has a chance to undo. I would avoid retriggering the dialog every time the user wants to undo the location, since adjusting the pin requires a lot of microadjustments. What if instead, we trigger the dialog after the user hits "Next", before moving on to the next task? That way, the user can adjust the location without retriggering the dialog and allow the user to go back to the LOI task if they decide they want to rename, making sure to load the previously selected name into the dialog. Here is a quick implementation sketch:

1. Use `Composable` dialogs to create the dialog, instead of using XML -> Fragment -> ViewModel system.
1. Trigger the dialog in `DataCollectionViewModel` and save the LOI data in a persistent manner.
1. Send the LOI data to `SubmitDataUseCase` where it will be saved locally then later sent remotely.

![image](https://github.com/google/ground-android/assets/12646706/b4b50aed-06b9-47e1-a53c-c41cd575c6b9)

WDYT, @gino-m?

**Comment by gino-m** [comment]
@rawbzz ok to trigger the LOI name dialog after the user clicked "Next" for the reasons @sufyanAbbasi mentions above?

In terms of implementation, that all sounds good with one delta - iirc SubmitDataUseCase represents the user hitting the "submit" button at the end of the data collection flow. The data collection flow keeps internal state with all the user responses, I assume the LOI name would belong in there until the data collection flow is completed.

**Comment by rawbzz** [comment]
Ah yea that makes sense..It wouldn't be good for the dialog to trigger every time the user tries to move the pin. I think it sounds good that once they drop the pin and move it around to the exact location and then pressing "next"  has the dialog come up.

**Comment by sufyanAbbasi** [comment]
Thank you so much @rawbzz for the leniency! This is the rare occasion when taking the simpler approach doesn't detract from the UX :).

Makes sense, @gino-m. `SubmitDataUseCase` is where we extract the final LOI data from the LOI task of a given job in `addLocationOfInterest()`, so the challenge will be to figure out how to pipe the LOI name into here for property construction.

For 2) We will want to save the `loiName` to the local DB alongside `loiID` in `DraftSubmissionEntity` where it can be recovered in draft state. I will also use a new `saveState` key, `TASK_LOI_NAME_KEY` to handle fragment refresh etc.

<img width="804" alt="Screenshot 2024-03-07 at 2 57 38 PM" src="https://github.com/google/ground-android/assets/12646706/ddee5cef-4b1b-47e2-b21e-1276e5be282d">

**Comment by gino-m** [comment]
That makes sense based on my fuzZy recollection. If you like, send a scratch PR so we can discuss in context!

**Comment by sufyanAbbasi** [comment]
Edit on 1) I found success in intercepting the "next" click handler on the `AbstractTaskFragment`, detecting whether the task is an LOI task and open the dialog, set the LOI name on the linked `DataCollectionViewModel` from the `AbstractTaskFragment`. From there it seems to work as intended!
