### ISSUE TITLE
[Draw an area] Rename to "Draw or walk perimeter" in UI

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2341]
For clarity and for consistency with web.

@sufyanAbbasi PTAL?

**Comment by sufyanAbbasi** [comment]
On it!

**Comment by sufyanAbbasi** [comment]
Actually, I'm not sure where in the UI you'd like me to update, since the label for the draw area task is dynamically decided by the user.

The only text we have related to draw area is the instructions, which say: `Move the map and tap “Add point” to add points around the desired area`, which can probably say something like `Move the map or walk the perimeter and tap “Add point” to add points around the desired area`?

**Comment by gino-m** [comment]
> Actually, I'm not sure where in the UI you'd like me to update, since the label for the draw area task is dynamically decided by the user.
> 
> The only text we have related to draw area is the instructions, which say: `Move the map and tap “Add point” to add points around the desired area`, which can probably say something like `Move the map or walk the perimeter and tap “Add point” to add points around the desired area`?

Ah, good point! Only challenge is explaining how that they should enable "location lock", since we never refer to it as such, and we never teach them where that is. @amegantz @rawbzz for ideas.

**Comment by amegantz** [comment]
Please tag me in the Figma as I'm a little confused about the context for this one!

**Comment by gino-m** [comment]
We're rethinking how polygon/point tasks work, so this is now obsolete.
