### ISSUE TITLE
[Capture location] Location permissions requested on wrong task

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2388]
Location permission dialog was shown on preceding task rather than on the capture location task.

@sufyanAbbasi FYI

**Comment by sufyanAbbasi** [comment]
May be related to a recent change that allowed for more offline robustness to permission changes:
https://github.com/google/ground-android/pull/2334

**Comment by sufyanAbbasi** [comment]
Added a breakpoint at `BaseMapViewModel:enableLocationLockAndGetUpdates()`, it seems that it is due to:

1. `CaptureLocationTaskMapFragment:onMapReady()` is called that will attempt to obtain permissions from the user, as soon as it is
2. triggered by `AbstractMapContainerFragment:onViewCreated()` when the
3. `GoogleMapsFragment:attachToParent()` is called, presumably loaded beforehand for efficiency.

This causes the eager permissions popup to show up.

**Comment by sufyanAbbasi** [comment]
Instead of greedily turning on location capture when the map is rendered (which can happen anytime), we can wait to turn it on when the user hits "Capture" when the location lock has not already been turned on. Then this option should prompt the permission checker. Interestingly, if the location lock is already turned on, I believe that we don't need to have `onMapReady()` do it again.
