### ISSUE TITLE
[Offline sync status] Duplicate entries shown in status screen

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2389]
**Describe the bug**
When adding a new LOI, two entries appear, one of which never completes.

**To Reproduce**
1. Add a new LOI and collect data
2. Open sync status screen

**Expected behavior**
There is only one entry shown for the LOI, submission, and photo.

**Actual behavior**
Two entries are shown, one of which never finishes.

**Screenshots**

![Screenshot_20240317-105913.png](https://github.com/google/ground-android/assets/228050/9b590ee0-6a9b-4bf4-886a-6625a96d53c6)

![Screenshot_20240317-105937.png](https://github.com/google/ground-android/assets/228050/451900f5-941c-4e60-8e8e-e3ae820036f3)

![Screenshot_20240317-105952.png](https://github.com/google/ground-android/assets/228050/6511a521-66e2-4759-ae6d-a93ea0614e41)

@scolsen PTAL? @jcqli for tracking.

**Comment by gino-m** [comment]
@shobhitagarwal1612 Could you PTAL this one, related to sync status screen?

**Comment by shobhitagarwal1612** [comment]
While investigating into it, I found that we only mark the status SubmissionMutations as "COMPLETE" since it is only done in MediaUploadWorker which ignores LoiMutations.

There are 2 potential solutions for this:

1. We assume that LOI Mutation **can never** contain any media. Then we can set the status for LoiMutations directly as done instead of "Pending for media upload"

2. We assume that LOI Mutation **might** contain media in future. In this case, we'll have to update the media upload worker to not filter out loi mutations.

Recommendation: Given that LoiMutation is also composed up of tasks, it is not impossible to add a task in LOI creation flow which requires media upload flow. But it requires slightly more effort for 2 than 1. Therefore, it makes sense to go with option 1 if LOIs will never have media tasks. Otherwise, we should opt option 2.

In addition to the above decision, we also need to add another text field in the displayed card to differentiate between "Submission" and "LOI" mutations.

@gino-m @sufyanAbbasi Please share your thoughts?

**Comment by gino-m** [comment]
> Additionally, we need to introduce another text field in the displayed card to distinguish between "Submission" and "LOI" mutations.

Thank you @shobhitagarwal1612 for the thorough investigation. The user doesn't think of the data collection flow as "LOI, Submission, and Media" mutations, but rather as a single flow. In that case, would be possible to group all three types by some ID (a new data collection flow ID?) so that they can be correctly grouped as a single action? I believe that would make several of the questions you mentioned moot. Lmkwyt.

**Comment by shobhitagarwal1612** [comment]
But from implementation point of view, do we ever expect LoiMutations to contain media related tasks?

**Comment by gino-m** [comment]
> But from implementation point of view, do we ever expect LoiMutations to contain media related tasks?

No. :)

**Comment by shobhitagarwal1612** [comment]
> The user doesn't think of the data collection flow as "LOI, Submission, and Media" mutations, but rather as a single flow. In that case, would be possible to group all three types by some ID (a new data collection flow ID?) so that they can be correctly grouped as a single action?

One LOI (predefined or adhoc) can have multiple mutations. So, it is not feasible to group mutations by LOI. Possible options:

1. Keep the LOI mutation but add a different label to it
2. Hide the LOI mutation once the sync is complete
3. Don't show the LOI mutation at all in sync status screen
4. Create a separate screen or section for LOI mutations

**Comment by gino-m** [comment]
If it's not much more work, my preference would be to link them all by some common, new "collection" or "add/edit" ID that is assigned to each time to data collection flow is opened. That way if we add "edit" in the future, changes can be grouped by user action (i.e. the user opened "collect" or "modify data", went through the flow, and hit submit/save). Is that possible?
