### ISSUE TITLE
Ant import order check doesn't honor google java-lang-format import order

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#240]
Our current lexicographical import order check and the import order auto applied by the java formatter we're using disagree. 

e.g. running the formatter yields the following import order:

```java
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;

import com.google.android.gnd.MainActivity;
import com.google.android.gnd.R;
import com.google.android.gnd.databinding.OfflineAreaManagerFragBinding;
import com.google.android.gnd.inject.ActivityScoped;
import com.google.android.gnd.ui.common.AbstractFragment;
import com.google.android.gnd.ui.common.TwoLineToolbar;

import butterknife.BindView;
```

Which fails our ant lexicographical import order check:

```
[ant:checkstyle] [ERROR] /workspace/gnd/src/main/java/com/google/android/gnd/ui/offlinearea/OfflineAreaManagerFragment.java:35: Wrong lexicographical order for 'butterknife.BindView' import. Should be before 'com.google.android.gnd.ui.common.TwoLineToolbar'. [CustomImportOrder]
```

**Comment by scolsen** [comment]
Maybe a better question is why the java formatter puts butterknife last, I have no idea.

**Comment by gino-m** [comment]
@shobhitagarwal1612 Can we fix the import order config to match https://github.com/google/google-java-format?

**Comment by shobhitagarwal1612** [comment]
I'm using google java format plugin and imported the provided XML into Android Studio.

**Comment by gino-m** [comment]
> I'm using google java format plugin and imported the provided XML into Android Studio.

I think the issue was that google-java-format produces an output in this case that isn't accepted by checkstyle (see scolsen's example above).

**Comment by shobhitagarwal1612** [comment]
It works for me! I'll share the link of the xml that I'm using.
https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

https://plugins.jetbrains.com/plugin/8527-google-java-format
See the first review by Aaron Pieper. It says that the plugin doesn't handle the import order by itself. Importing the above mentioned xml does the trick.

**Comment by gino-m** [comment]
I didn't realize we needed a custom config for the formatter. Good find!

Would it make sense at this point to check in a subset or all of the
Android Studio configuration, so that this an other setting can be provided
automatically?

>

**Comment by shobhitagarwal1612** [comment]
> Would it make sense at this point to check in a subset or all of the
Android Studio configuration, so that this an other setting can be provided
automatically?

I tried that and it works. The only problem is, there would be inconsistency if we continue using the `google-java-format`. So, either we remove plugin and check-in the project level styling for automatic configuration or add instructions to do it manually as in #243

**Comment by gino-m** [comment]
Ah! So I thought intellij-java-google-style.xml was a custom config for google-java-format, but it sounds like it just reconfigures the default formatter. If that's the case I'm in favor of using that instead of the plugin to simplify the environment set up, especially if the formatting implemented by that config matches the CI lint rules.
