### ISSUE TITLE
[Bug] Terms of service screen is skipped if network is not available when the app is opened for the first time.

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2657]
**Describe the bug**
Terms of service screen is skipped if network is not available. Instead it skips to the survey selection screen and the terms of service screen is showed on the next app reopen.

**Comment by gino-m** [comment]
Having a little trouble resolving this because we actually load the ToS twice, once to know whether to go to the ToS fragment, and once when the fragment is loaded. I'd like to not have to handle errors in both flows, but the sign in flow is very complex, and passing the text through the _uiState flow and Fragment args is not trivial atm. Still brainstorming options...
