### ISSUE TITLE
Why are we using last project id when loading a new project by id?

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#273]
Wasn't sure if this was a bug or intended?
https://github.com/google/ground-android/blob/2e8ed982d7b40d82d1a6e3d02f2ad106d5247647/gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java#L121-L139

**Comment by scolsen** [comment]
Hm, yeah seems like a slight error here... It looks like we only use the last project id if we fail to load the project from the remote, but really we should be loading the local version of whatever project we attempted to fetch instead of the last active project--right?

Really the sequence should be something like:

- get project from remote
- if fail, get project from local
- if fail, use last active project

And we should report the errors to the user on each failure case....

In general this method's a bit tough to digest. It doesn't look as though it even marks the loaded project as active! (But maybe that happens in the onProjectLoaded callback)?

**Comment by shobhitagarwal1612** [comment]
Agreed, it's a fault on my side. I'll fix it.

**Comment by gino-m** [comment]
No worries! Just wanted to make sure I didn't misunderstand. I'm revising
the activate project flow and sending a draft PR with the general id
shortly. Want to wait until I get that out?

**Comment by gino-m** [comment]
This was fixed in a recent PR so marking closed.
