### ISSUE TITLE
[Data sync] Sync status stuck on "Syncing media" for some items

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2751]
@jo-spek @n-clinton @jabramowitz5 have reported sync stuck or data potentially being lost. Potentially related to #2738.

**Comment by jcqli** [comment]
@jabramowitz5 is this still reproducible?

**Comment by jabramowitz5** [comment]
In conversation with data collector and checking the data entries synced to web app, it seems like the error was in the app not indicating the data was successfully synced, rather than an actual error with the data not syncing. Bashara indicated that the entries data collectors had that were showing as "syncing" or "media syncing" were actually already synced and available for download in the web version. So I am thinking it is a sync status (messaging?) issue rather than data actually being lost.

This was before the update to 0.1.10 for users, because these data collectors were delaying update for fear of losing data showing as "syncing"

**Comment by gino-m** [comment]
@jabramowitz5  There was an issue when the sync failed before the status could be updated - I've posted a fix in https://github.com/google/ground-android/pull/2844 to force these to complete. This workaround will only work once @rfontanarosa cuts a new release, data collectors install the release, and open the app main home screen (the map).
