### ISSUE TITLE
[Download Area - Landscape] Landscape Support UI Required

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2795]
![Image](https://github.com/user-attachments/assets/5fa95a75-9214-43b0-b333-9e7ebd89ac25)

Currently, the UI of the Download Area screen looks like the above screenshot, which is hard for user to use.
We need landscape based screen UI.

**Comment by rawbzz** [comment]
@gino-m  I'm thinking we need to update the design so the background containers for both the header and buttons are transparent, otherwise theres no way to make more of the screen show. Additionally, wondering if we are able to hide the clock and cell bars on landscape mode to give us more height? The top is with the clock bar and bottom screenshot is without

![Image](https://github.com/user-attachments/assets/cd0a8dea-e39b-41c7-88fd-24fd86f2c285)

**Comment by gino-m** [comment]
We spoke with @anandwana001 and @kenstershiro. @rawbzz Hiding the system tray is non-trivial and would only give us a few pixels anyway. Let's submit a fix for the crash first. The current UI isn't ideal, but improving it isn't high priority at this point.

**Comment by gino-m** [comment]
@anandwana001 If this is working please close and this issue.

**Comment by anandwana001** [comment]
Yes, it's working fine on Landscape mode
