### ISSUE TITLE
Bottom sheet Expanding and collapsing too fast.

### ISSUE THREAD

**Issue by mtariquekhan** [google/ground-android#36]
Whenever I set the state of the Bottom Sheet to expand mode then it gets expanded too fast.
Is there any way to control the expanding and collapsing animation speed?

**Comment by gino-m** [comment]
Hi @mtariquekhan, do you mean when you swipe up it snaps to full height? If so that's by design; we do this to avoid the map showing too few pixels of vertical height, in which case it might be confusing and/or not useful.

If that's not it, please feel free to attach a screen capture and I can try to diagnose further.

**Comment by gino-m** [comment]
Can't reproduce so marking closed for now. If you can provide more details happy to investigate.
