### ISSUE TITLE
[Map] Adjust marker size based on zoom level

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#364]
Zoom level < 16:
![image](https://user-images.githubusercontent.com/228050/74393992-8f8f5a00-4dd9-11ea-8d6d-0168520b12be.png)

Zoom level >= 16:
![image](https://user-images.githubusercontent.com/228050/74393978-84d4c500-4dd9-11ea-9072-6809f00bb60e.png)

**Comment by JSunde** [comment]
I think I can take a stab at this. Gino, do you have any suggestions for modifying the scale on the fly? It looks like today the marker is created once in the MarkerIconFactory, so changing the size based on the zoom level there won't have any effect since the zoom level will always be the default value when the marker is created.

**Comment by gino-m** [comment]
> I think I can take a stab at this. Gino, do you have any suggestions for modifying the scale on the fly? It looks like today the marker is created once in the MarkerIconFactory, so changing the size based on the zoom level there won't have any effect since the zoom level will always be the default value when the marker is created.

Sure, please go ahead! I think you may need to handle this in the view model when the camera changes, updating the MapMarkers accordingly. Please ping if you get stuck and we can look at it together!
