### ISSUE TITLE
[Feature sheet] Gap between bottom of sheet and system inset when expanded

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#366]
I was unable to get bottom sheet to fill the viewport when there weren't enough observations in the list to expand it to full height; hard coding `height` and `minHeight` on various layout components had no effect.

**Comment by shobhitagarwal1612** [comment]
Can you please attach a screenshot?

**Comment by gino-m** [comment]
I plan to take this to speak to a colleague who works on Android MD components to debug, please disregard for now!

**Comment by gino-m** [comment]
This is likely a result of is holding it the wrong way - the current bottom sheet + map implementation is a bit messy. If there's a cleaner, canonical way of configuring the layout and fragments it probably prevent UI glitches like this one.

To repro, add a point to the map (hit +, select layer) or tap and existing point, then scroll the sheet up to full height.

**Comment by gino-m** [comment]
![Screenshot_20200305-083545](https://user-images.githubusercontent.com/228050/75986587-5ae45f00-5ebc-11ea-9ace-bdd5876f5572.png)

**Comment by dturner** [comment]
I'm sorry I don't see the issue. Is it that there's a dark blue line under the +Observation FAB? Or that the title "Community limit" is not vertically aligned to the center of the title bar?

**Comment by gino-m** [comment]
> I'm sorry I don't see the issue. Is it that there's a dark blue line under the +Observation FAB? Or that the title "Community limit" is not vertically aligned to the center of the title bar?

It's the dark blue line - that line is because the sheet height isn't stretching to fill the viewport, and the background is peeking out.

**Comment by gino-m** [comment]
Note that although the issue is only aesthetic, I think our inability to fix it may be due to using BottomSheet and CoordinatorLayout incorrectly.

**Comment by dturner** [comment]
I couldn't repro on Pixel 3 device and Pixel XL emulator. Here's what I see on the Pixel XL:

![image](https://user-images.githubusercontent.com/873212/76531183-bf7b5d00-646c-11ea-99a8-05d71ceda1bb.png)

Which device(s) are you seeing this on?

**Comment by gino-m** [comment]
Looks like you're on a super old version of the codebase - please `git pull upstream master` and try again!

**Comment by dturner** [comment]
With latest head I can repro.

**Comment by dturner** [comment]
Been looking at this today. Here's what's happening: 

- The height of the bottom sheet is defined as `match_parent` in `home_screen_frag.xml`: 

            <FrameLayout
          android:id="@+id/bottom_sheet_scroll_view"
          android:layout_width="match_parent"
          android:layout_height="match_parent"

- The sheet contains both the header (defined in `feature_sheet_header.xml`) and the observation list (defined in `observation_list_frag.xml`)
- When you expand the bottom sheet the top of the list is aligned with the bottom of the app bar and the feature header is completely hidden (it is redundant because the title of the feature is shown in the app bar)
- As @gino-m said, the background shows through because the bottom sheet is not tall enough. I think it should be: `feature header height + parent height`. 

@gino-m @shobhitagarwal1612 Since this has to be set dynamically, is there a good place in the code to set this?
