### ISSUE TITLE
[Background sync] Use foreground service / workers for sync

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#430]
Originated from #421 @gino-m. says, 

> Q. Foreground service should be running at all times or periodically?
> A. Two planned features will require the service to be run at all times: GPS tracks recording, and syncing added/changed/removed features from joined remote projects to the local device.
> 
> Q. Clicking the "App is running" notification should perform some action?
> A. I assume clicking the notification will take us back into the app home for now. In the future we could also direct to a more detailed status page.
> 
> More general question - what belongs in the Workers (if anything) vs in the foreground Service? On the one hand, it would simplify implementation and give us greater control to sync all data in the same service. On other, with worker we get job constraints (network availability, for example) and parallelism for free.
> 
> One possible prioritization of tasks could be:
> 
> Upload local changes to observations and features (except photos)
> In parallel (?):
> a. Smaller new/changed features in joined projects
> b. Download satellite imagery
> c. Upload photos
> d. Upload new GPS tracks data [TBD]
> There may be two options in settings to constrain when smaller syncs (1 and 2a) and larger ones (2b, 2c) can be executed. I wonder if all sync should be done in the service because:
> 
> The user can change the sync constraints after a sync task is queued. If the worker is already queued, we'd need to add logic to handle this, possibly by aborting and requeueing with the new constraints. (this adds complexity and carrying cost)
> It's not obvious how to implement the ordering of our idempotent workers wrt our queue and network constraints. Putting them in one service might make it clearer how these various tasks interact.
> Curious to hear your thoughts, incl. @scolsen @dturner? Thanks!

**Comment by scolsen** [comment]
There are some android docs on choosing the right approach that might be helpful: https://developer.android.com/guide/background#choosing_the_right_solution_for_your_work

From what I can tell, it seems as though the primary consideration is user awareness and timing control, if we want to have precise control over what happens when, foreground services are the way to go:

> For user-initiated work that need to run immediately and must execute to completion, use a foreground service. Using a foreground service tells the system that the app is doing something important and it **shouldn’t be killed**. Foreground services are visible to users via a non-dismissible notification in the notification tray. (emphasis mine)

> Foreground services are most appropriate when the app needs to have precise control over when the work stops and starts.

Whereas workers are recommended for work that must complete but is deferrable until certain constraints are satisfied:

> For work that is deferrable and expected to run even if your device or application restarts, use WorkManager. WorkManager is an Android library that gracefully runs deferrable background work when the work's conditions (like network availability and power) are satisfied.

I think what makes the situation difficult for us is the conflicting properties of each thing we're trying to achieve. Basically, this doc suggests we should consider, for each job, its **importance**, the **level of control we need** and whether or not it's **deferrable**

 For example, keeping projects/features up to date seems incredibly *important*, but also seems *deferrable* to the extent that, if our conflict resolution is sophisticated enough, one can reasonably work with a project offline and sync once a connection is restored (indeed, this is one of our key selling points).

Contrarily, the importance of uploading a photo and downloading imagery can vary considerably. If someone's out in the field and needs to upload a photo immediately so that others can react to a real-time situation, then yes, that's very important and arguably work we should ensure executes to completion in a foreground service. Yet there are other scenarios in which one just wants to upload some photo in the background while performing other, more crucial data entry work at the project level...

Personally, I'd lean toward handling anything that's more or less incremental and happens often in workers (like keeping projects up to date), and anything that's more expensive in a foreground service (where the user could conceivably cancel it?) that way we prevent situations in which we spin up an expensive job from scratch multiple times. But idk, I think it really comes down to understanding our users and what they'd prioritize.

**Comment by scolsen** [comment]
> All that being said, should we just promote all three workers to foreground services? Would doing all three in a similar fashion simplify our implementation?

Sounds good to me!
