### ISSUE TITLE
[Code style] .idea/codestyles/Project.xml occasionally changes by itself, blocking pull/merge

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#543]
@shobhitagarwal1612, is allowing this file in git recommended, or is there another/better way to share the Android Studio configs?

**Comment by shobhitagarwal1612** [comment]
There is an option of `settings repository` in Android Studio for sharing settings across the team. 

https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html#settings-repository

I can take a first stab at this.

**Comment by gino-m** [comment]
Great, thanks for taking a look!

**Comment by shobhitagarwal1612** [comment]
Hi @gino-m 

I tried creating a [sample settings repository](https://github.com/shobhitagarwal1612/test_settings_repository) and it worked as expected. (Also sent you an invitation to check out the repo)

So, the next steps should be:

1. Create a new repository (preferably private) where we'll keep our IDE settings.
2. Enable `settings repository` under Preferences > Plugin
3. Set the URL from step 1 under File > Settings Repository > Upstream URL. Then select 'Overwrite Local'

From this point onwards, the plugin should auto update the local settings whenever there is an update.

**Comment by shobhitagarwal1612** [comment]
@gino-m Please ignore my last comment, it is still in progress. Some files were excluded during the sync which are a part of codeStyle.

**Comment by shobhitagarwal1612** [comment]
If we save the codestyle in the IDE rather than project then it works!
https://github.com/shobhitagarwal1612/test_settings_repository/blob/master/codestyles/ground-android.xml

To apply the settings:
Preferences > Editor > Code Style > Click of "Scheme" drop-down > Select "ground-android" under Stored in IDE.

@gino-m 
I have pushed the changes to my test settings repository. To test the changes:
1. Create a fresh clone of the project for testing
2. File > Settings Repository > Set url: https://github.com/shobhitagarwal1612/test_settings_repository/  and click overwrite local
3. Then select "ground-android" as preferred code style under Preferences (steps mentioned above)

**Comment by gino-m** [comment]
We spoke - we can't rely on repos owned by individuals or other orgs, and the inconvenience this issue causes is minor, so I think we will skip this one for now. Thanks for looking into it!
