### ISSUE TITLE
[Code health] Verify exceptions are either wrapped or handled in all Rx streams

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#84]
We can rename `Result` to something like `ValueOrError`, and wrap the value at the source, obviating the need to wrap/unwrap at arbitrary steps in the stream.

@scolsen FYI.

**Comment by gino-m** [comment]
Should we really though? Posted [this question](https://groups.google.com/forum/#!topic/rxjava/sIFNQng5yg4) asking about an alternative approach, a là:
```
    disposeOnClear(
        addFeatureClicks
            .switchMap(
                f ->
                    dataRepository
                        .saveFeature(f)
                        .doOnComplete(() -> showFeatureSheet(f))
                        .doOnError(t -> onAddFeatureError(t))
                        .onErrorComplete()
                        .toObservable())
            .subscribe());
```

There's not need for a wrapper unless we want to propagate errors across long-lived streams. Since Rx streams obtained imperatively will return Completable, Single, or Maybe, this will usually only happen when declaratively setting up and subscribing in ViewModels.

**Comment by gino-m** [comment]
@scolsen, I discussed this with ex-colleagues at FAO (@cdanielw, @lpaolini) who work with RxJS extensively on [SEPAL](https://github.com/openforis/sepal), and consensus is that it's better to wrap and unwrap in some intermediate object to represent errors as a value rather than at stream level (as we have now), rather than to rely on side-effects on the inner stream, e.g.:

https://github.com/google/ground-android/blob/fd1324aa8e59159c9941c5dfab6c7c082cff0b6f/gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java#L62-L67

My guest is that with some additional syntactic sugar and clearer naming we can make this more self-documenting / obvious without sacrificing FRP "purity".

**Comment by scolsen** [comment]
Sounds good! Let's stick with our basic idea then and iterate on improving the clarity of the semantics. 

`ValueOrError` is fairly straightforward. 

Would it be clearer to the majority of Java/Android devs if we emulated or took inspiration from an existing interface like `Optional`? i.e. instead of doing something like `unwrap` doing something like `orError` -- this particular example doesn't sound like a great idea to me, just speculating here haha, but maybe it's an approach we can consider.

**Comment by gino-m** [comment]
Yes, I was thinking the same thing. Afaict, the closest use of Optional is
Java 9's "ifPresentOrElse()". What would the equivalent be here?
ifSuccessOrElse?

**Comment by scolsen** [comment]
`ifSuccessOrElse` sounds right to me!

Do we prefer `ValueOrError`, `Result`, or `SuccessOrError`?

I like `Result` because it's concise, but I could see it being a bit less understandable from the perspective of someone unfamiliar with the code base. 

I think we'll want to change `mapSingle` and `mapObservable` to match too. Since `Optional` uses `of` how about: `ofSingle` `ofObservable` etc?

Or we could do a little bit more work on the API design side to expose only an `of` method -- this would make it really easy to use in practice as we wouldn't have to recall the particular type of item we're wrapping--I don't see any immediate value in making users recall which types they're wrapping (having to use particular `ofSingle` etc methods) since once it's wrapped it no longer matters, really. 

I think my preference is for something like the following:

**`Result`**
* `of(<Function<Observable|Flowable|Single|...> stream)` : Wrap RX types, `Observable`, `Single` etc.
* `ifSuccessOrElse(<Function<Result::Success>> f, <Function<Result::Error>> g)` : Unwrap a result value calling f on success, g on error.

Note here that `of` is taking the place of our mapping functions `mapSingle` etc.

I think we more or less decided we don't need our current `wrapSingle` and `wrapObservable` methods (wrap into a result using identity, not a mapping function) but if we do we can overload `of` to take RX entities directly in addition to a function, or we can provide a method like `from`. 

`Of` taking a function (since it's actually a map) is a little odd at first glance, but I think it works in practice and reads pretty well (example after the paragraph below).

Overloading generic methods (polymorphic methods) in Java is a bit messy because of type erasure. So unfortunately we can't just implement something like `of` over any RX type using overloads. Instead I think(?) we'll have to do something like define private methods for each type that the `of` method dispatches to somehow--so it's a little more work on our side, but it makes using wrapper class dead simple:

```
 this.activeProjectStream = 
     projectSelections.switchMap(Result.of(this::selectActiveProject)); 
  
 disposeOnClear( 
     activeProjectStream.subscribe( 
         Result.ifSuccessOrElse(activeProject::setValue, this::onActiveProjectError))); 
```

Another alternative if we need to wrap using identity: 

**`Result`**
* `of(<Observable|Single|...> stream)`
* `from(<Function<Observable|Single|...>> stream)`
* `ifSuccessOrElse(<Function<Result::Success>> f, <Function<Result::Error>> g)` 

Or we could make the function argument to `of` optional such that `projectSelections.switchMap(Result::of)` is valid and wraps the stream without performing any mapping.

Or if we want to make it really obvious we could even do something like `Result.ofMapping(f)`

I don't like the obvious choice of `Result.map` only because I think it's easy to confuse that method as mapping over a `Result` because of the way `map` is typically used--instead of mapping over something and returning a result(which is what it'd actually be doing).

`Result|ValueOrError|SuccessOrError.of` seems to me to be the shortest and clearest.

**Comment by gino-m** [comment]
I'm partial to `ValueOrError` because of existing precedent in some C++ libraries. On the other hand, I also like `Result` because it's less verbose. I'll need to see it used in context to get a sense of how clear it is. 

Regarding `of()`, I remember reading a [blog post](https://blog.danlew.net/2015/03/02/dont-break-the-chain/) always suggesting using `compose()` to mutate streams in Rx, since it represents stream mutations in a way that's consistent with other operations. I also have mixed feelings about how much logic should be hidden inside the helper (hidden but more concise), in which case you may need to know something about what the helper does, vs. represented using Rx idioms (more explicit, less to learn, more verbose). 

So in other words, rather than wrapping with `of()` or calling `compose()`, we may just use Rx methods like:

```java
    disposeOnClear(
        addFeatureClicks
            .switchMapSingle(
                f ->
                    dataRepository
                        .addFeature(f)
                        .map(ValueOrError::value)
                        .onErrorReturn(ValueOrError::error))
            .subscribe(voe -> voe.ifValueOrElse(this::showFeatureSheet, this::onAddFeatureError)));
```

We could also use `compose`, but it only saves one line in each declaration:
```java
    disposeOnClear(
        addFeatureClicks
            .switchMapSingle(
                f ->
                    dataRepository
                        .addFeature(f)
                        .compose(ValueOrError::mapValueOrError)
            .subscribe(voe -> voe.ifValueOrElse(this::showFeatureSheet, this::onAddFeatureError)));
```

Still meditating on this one. Other ideas welcome.

**Comment by scolsen** [comment]
`ValueOrError` is cool with me!

I'm somewhat confused by the code samples you suggested--what does the wrapper grant us at that point? I might be missing something, but I thought the major benefit of the wrapper was that it ensured errors are handled without having to call `.onErrorReturn` explicitly on each point at which we return an inner stream--but we're doing that anyway in your first example. `switchMap` propagates whatever errors are returned by the inner stream up to the enclosing stream and cancels subscriptions to the inner stream. So, we could just stick with pure RX for this particular example:

```java
disposeOnClear(
        addFeatureClicks
            .switchMapSingle(
                f ->
                    dataRepository
                        .addFeature(f))
            .subscribe(this::showFeatureSheet, this::onAddFeatureError);
```

I might be missing something, but this should just work as is. switchMap flattens the outer stream to return whatever the inner stream emitted (feature or error) if that happens to be an `Single.error` `onAddFeatureError` is called, if it happens to be a feature `showFeatureSheet` is called.

In fact I tried this exact example in our current code base. Forcing an error in the inner stream works as expected. Since there's still a good chance I'm misunderstanding something here, here's the modification to see it in action:

In the data repository:

```java
public Single<Feature> addFeature(Feature feature) {
    return Single.error(new Throwable("No features to add here."));
    //return remoteDataService.addFeature(feature);
  }
```
In the HomeScreenViewModel

```java
disposeOnClear(
        addFeatureClicks
            .switchMapSingle(dataRepository::addFeature)
            .subscribe(this::showFeatureSheet, this::onAddFeatureError));
```

When run, if you try to add a feature, nothing will happen, `onAddFeatureError` is called, the throwable is logged, and the app keeps running. So, presumably, RX will do the right thing when we use this approach if the actual returned stream `remoteDataService.addFeature()` returns a Single.error.

It's also possible that this is not a good example case, and that we'll need wrappers for other situations, but it doesn't look like we'd need them if all we're doing is flatmapping or switchmapping over a single 
inner stream. 

I think the only case that's actually problematic is when we're jumping from RX land to `LiveData` land using `fromPublisher`--I believe in that case we *must* use `onErrorReturn` because `LiveData` doesn't offer a similar mechanism to subscribe's error callback to handle errors when deriving livedata from a stream. *But*, if my thinking is correct, this is not a problem with `MutableLiveData` as in that case we'd simply stick with RX subscriptions and only call the MutableLiveData set function on a successful emission, and do something else on errors. 

The only difference with flatMap afaik, is that it doesn't cancel the existing subscriptions to the inner stream, thus, if we had a situation like (in pseudocode):

```
bar = dataRepo::addfeature(foo);
bar.subscribe(this::onAddFeature)
clicks.flatMap(x -> bar).subscribe(this::onAddFeature, this::onFeatureError)
```

The app returns the following as soon as the HomeScreen VM is instantiated, because we don't provide an error cb in the first subscription:

```
E/RxDebug: Unhandled Rx error
    java.lang.Throwable: Fear the feature
        at com.google.android.gnd.repository.DataRepository.addFeature(DataRepository.java:184)
        at com.google.android.gnd.ui.home.HomeScreenViewModel.<init>(HomeScreenViewModel.java:146)
        at com.google.android.gnd.ui.home.HomeScreenViewModel_Factory.get(HomeScreenViewModel_Factory.java:22)
        at com.google.android.gnd.ui.home.HomeScreenViewModel_Factory.get(HomeScreenViewModel_Factory.java:9)
        at com.google.android.gnd.ui.common.ViewModelFactory.create(ViewModelFactory.java:50)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:135)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:103)
```
Using switchmap, we still get the error on instantiation since we subscribe to the first stream immediately, the difference is, afaict, that after the switchmap succeeds once the original subscription is cancelled, so you'll no longer see the RX error after clicking the add button once. I'm not actually able to confirm this because there's a separate bug with the add button right now that makes it so that you can't add another feature after the first attempt errors.

All in all, then, the simplest thing might be to commit to using `MutableLiveData` and `subscribe` callbacks to handle errors, then we won't require any wrappers--unless there's a case I'm not thinking of or there's something I'm misunderstanding. For example, I'm not sure that this particular example counts as a long-lived stream, and I'm positive my hypothetical exercises don't.

In these investigations I've also discovered a separate issue--it turns out that because this stream is associated with the home screen VM lifecycle, if it fails to add a feature once, no subsequent adds work because the subscription is disposed (I believe what happens is the activity is cleaned up after the add dialog is cleared on failure) leaving the user on a home screen with a broken add button. So, this subscription should actually be happening elsewhere/should be associated with a different part of the lifecycle so that it isn't cleaned up and removed on clearing the dialog.

**Comment by gino-m** [comment]
Sorry to vacillate on this, but after more experimentation, I'm back to thinking handling errors with side-effects rather than stream values will lead to more readable, self-documenting code.

Consider this example, if you will:

```java
    disposeOnClear(
        addFeatureClicks
            .switchMapSingle(
                feature ->
                    dataRepository
                        .addFeature(feature)
                        .doOnError(this::onAddFeatureError)  // Handle errors.
                        .onErrorResumeNext(Single.never()))  // Prevent error from breaking upstream.
            .subscribe(this::showFeatureSheet));  // Handle success case.
```

And compare with its "pure" equivalent using `ValueOrError`:

```java
    disposeOnClear(
        addFeatureClicks
            .switchMapSingle(
                feature ->
                    dataRepository
                        .addFeature(feature)
                        .map(ValueOrError::value)
                        .onErrorReturn(ValueOrError::error))
            .subscribe(voe -> voe.ifValueOrError(this::showFeatureSheet, this::onAddFeatureOrError));
```

Advantages of using side effects over (un)wrapping:

1. No need to extract ValueOrError class.
2. Boilerplate for wrap/unwrap errors is replaced with idiomatic, self-describing method calls.
3. Allows errors handlers to be declared individually in context for each downstream stream rather than upstream where offending stream is unknown.

This approach isn't functionally "pure", but a) neither is most our application, and b) for our purposes, afaict this is a purely theoretical drawback that won't manifest in practice. 

Rx itself treats errors as a property of the stream, that can be manually mapped to/from values if needed. This is perhaps the root cause of this impedance mismatch. But since errors are already a special case for Rx, I think we're on solid ground managing them as side-effects.

Note that errors must be handled downstream because if they're handled upstream, they still cause the source stream to break (just verified this manually, also described [here](https://medium.com/@jagsaund/5-not-so-obvious-things-about-rxjava-c388bd19efbc)). If you return a new Observable, the upstream (clicks) is replaces with it, breaking the flow.

Wdyt?

**Comment by scolsen** [comment]
I like it!

I agree that worrying about functional purity shouldn't be of high-priority when we're using RX--I think the most important thing is to stick with RX's semantics and definitions as much as possible--using side effects as you have here is a lot clearer and requires less work to grok for those that already understand RX Java (vs. having to learn about our own custom wrapper).

I think it also makes sense to conceive of "handling errors" *as* a side effect, which makes the use of the side-effecting operators clear--we want to do something to the stream's value (usually logging or displaying an error) without actually returning anything or modifying the contents of the stream (at that particular point). This is what I was trying to drive at with my suggestion to use these operations in #67 for UI related stuff, though I didn't express it very clearly and I think the title of the issue made it confusing since "pure" usually has a more pedantic meaning in the context of functional programming--I more so meant that we should express operations on RX streams using RX operators that signal our intent rather than tuck in additional logic in the functions passed to the mapping/transformative operators.

So it sounds like a good solution to me!

**Comment by gino-m** [comment]
Great, glad we're on the same page! tl;drs:

1. Ok to handle errors with onError*(), no need to wrap in value object.
1. With switchMapped streams, apply onErrorResumeNext() downstream where things can break; applying upstream is too late.
1. Avoid using onNext() and onSuccess() for non-error states, rather handle in subscribe().

I'll try to send out a PR for error handling this week.

**Comment by gino-m** [comment]
A few more thoughts while investigating adding consistent error handling:

* Where do we report errors to the user? Ideally all user-visible logic should live in views, which implies we'd like to report errors as far downstream as possible (i.e., in callers rather than functions returning streams). It might make sense for an eventual `ErrorHandler` class that requires a View context rather than the Application to make sure system classes aren't unexpectedly causing UI effects.
* This isn't always possible, however, since streams nested with `flatMap*` and `switchMap*` contain their own streams, which do not propagate errors, and if unhandled, break the outer stream. This implies we may want to at least wrap inner streams with `Result<>`.

**Comment by gino-m** [comment]
Snippet for wrapping/unwrapping mapped streams in `ValueOrError` objects:
https://gist.github.com/gino-m/efcfd158a4d6e4461ac17a1a064d8a7e

**Comment by gino-m** [comment]
> 2. With switchMapped streams, apply onErrorResumeNext() upstream (inside switchMap) where things can break; applying downstream is too late.

I was just verifying this and I'm not convince this is the case. Will double check.

**Comment by gino-m** [comment]
Updated description to clarify what we need to verify.

**Comment by gino-m** [comment]
@dturner Going through the code you may have noticed that we have inconsistent handling of error states, esp. wrt persistence. Some are propagated to the UI layer and handled there, while others are handled (logged and ignored) in the Repository layer. 

The most complex use case is when we read multiple map features from remote and sync them to the local db in a background thread, with the UI layer subscribing to changes in the local db. If one item in the list of fetched features is invalid, ideally we'd like to do something like:
1. Log what went wrong
2. Warn the user some data may not have been loaded, and
3. Ignore the faulty feature and continue

How far forward to the UI layer should we propagate these? Is it common to show a Toast message from the Repository layer for issues like these? It breaks some abstract and complicates testing, but may reduce code complexity.

Would you mind taking a look to see if there's a more consistent approach we should take?

**Comment by gino-m** [comment]
See also big refactor PR #371 for reference.

**Comment by scolsen** [comment]
@gino-m -- is this covered by #371? Should we close this in favor of moving to coroutines where we can handle exceptions directly in blocks?

**Comment by gino-m** [comment]
> @gino-m -- is this covered by #371? Should we close this in favor of moving to coroutines where we can handle exceptions directly in blocks?

Sorry just replying to this now. Agreed we should close this in favor of migrating to coroutitnes.
