### ISSUE TITLE
[Sync status] Include photo upload status in sync status

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#877]

**Comment by scolsen** [comment]
Starting to think about this, a few questions:

Presently, we don't have our own representation of photos. From what I can tell, we pull directly from the device and queue up an upload via the upload manager. The manager handles the complete lifetime of this work, if it fails it's the only place that we retry This gives us two options:

1. We keep the current "ephemeral" representation of photos—we don't have our own model, and we don't write anything to the db. At runtime, whenever a photo gets uploaded, we'll just have the work manager publish its status to some readable state that the UI can peek at. One implication of this is that we lose any "upload history" each time you exit the application. We can show you the syncs from your current session, but nothing beyond that.
2. We write minimal photo information (path, upload status) to the DB. Besides giving us a more persistent and stable place to read information from, this would also presumably give us better control of upload mechanics. We could backoff instead of retrying indefinitely and resume work at a later time (on next app start). e.g. on app start we can look in the DB and queue up any uploads that are in a state of failed/pending etc.

@gino-m Any thoughts on this?

**Comment by gino-m** [comment]
Great questions, thanks for pointing this out. #2 sounds like a better option to me. If we can do something lightweight to start with to get something working that would be ideal. Ultimately I think we'll want to group mutations by Submission, sorted by last change/sync date, but we can tackle that separately.

**Comment by jcqli** [comment]
Chatted tih @scolsen , this task is done. Closing (appears to be addressed in https://github.com/google/ground-android/pull/2242)
