### ISSUE TITLE
[Docs] Document best practices in WIki

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#88]
Some things to cover:

Rx:

* Naming conventions for Rx streams (discussion in #82).
* When to use `LiveData` vs. Rx streams.
* When to subscribe vs. transform streams.

Let's track other ideas here.

Misc:

* google-java-format for code formatting.
* Reference to architecture docs (#87).
* Emphasize key arch. tenets:
  * No business logic in views (Fragments, Activities)
  * No references from ViewModel to View, one ViewModel for each view plus shared ones.
  * Inject deps, don't `new`

GitHub:
 * PR workflow, assignees, approvers, etc.
 * Always tag issue numbers in PRs
 * Issues: naming convention, labels, Alpha milestone, etc.
 * Stacked PRs - how to do this with forks? (Q: do forked repos keep PR history after being deleted?)
  * Use your real email in commits if possible

**Comment by gino-m** [comment]
@scolsen FYI

**Comment by scolsen** [comment]
I've added https://github.com/google/ground-android/wiki/RxJava-Best-Practices as a start!

Since the wiki is more or less open we'll have to request reviews explicitly...I'll look into seeing whether there's a setup we can use that instead incorporates reviews into the wiki submission/editing process.

**Comment by gino-m** [comment]
Great work! Hope you don't mind a added some more content:
https://github.com/google/ground-android/wiki/RxJava-Best-Practices
