### ISSUE TITLE
[Workflow] Best practices for stacking / chaining multiple dependent changes for review

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#93]
Ideally, the solution would have the following properties:

1. The workflow for stacked PRs would be as close as possible to the normal PR workflow.
1. The same workflow would work for both maintainers and contributors.
1. It would allow any branch names to be used (i.e., no error-prone manual branch naming conventions).
1. It would prevent merging out of order and/or automatically merge in the right of order.
1. It would allow diffs to be done directly against dependent PR (i.e.,show diffs incrementally across PRs).
1. It would be easy to merge changes made in earlier dependent PRs in the chain with later ones.
1. It wouldn't require any special shell scripts or browser extensions to work.

There are several solutions posted on various blogs, but none I've found so far address all of the above. Recently, we've been experimenting with using a custom branch naming convention (`issue-##/master` and `issue-##/username/pr-##`) + GitHub's PR "base" feature to do this. This has several drawbacks:

* The solution requires chained PRs to be in the main repository so that maintainers can be assigned to review them. This obvious doesn't work for contributors, who can't add branches to the main repo. Assuming they could grant reviewers permission to review directly in their fork (extra manual step), keeping PRs in contributor forks would make them hard to find (or at worse, ephemeral, since users can delete their forks).
* It litters the main repo with many working branches that need to be cleaned up.
* It requires manual merging up the stack during review.
* It requires the reviewer to know the shouldn't merge the PRs themselves.
* It requires the contributor to merge in a specific order, starting with the last PR down to the first to collapse and merge the stack.

Several alternatives considered that don't meet all of the above criteria:

1. Use commits as a proxy for units of work; create one big PR and review each commit individually. https://jg.gg/2018/09/29/stacked-diffs-versus-pull-requests/
1. Do running PRs, where contributors request feedback for a small unit of work, and merge in changes only after each round of feedback.
1. Using a Chrome extension (requires full read/write access to all browser data!), and not clear if this works across forks.
1. https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/: Doesn't work across forks either, manual process.

See also:
* https://github.com/isaacs/github/issues/867
* https://github.com/isaacs/github/issues/959
* https://github.com/isaacs/github/issues/210
* https://github.com/dear-github/dear-github/issues/112

There are more but I can't remember now. @navinsivakumar @scolsen @gyarill any thoughts?

**Comment by navinsivakumar** [comment]
I know that `git rebase` is considered scary and a lot of guides discourage it when pulling in changes from other branches, but I think there is a workflow for stacked PRs that would do what we want by using rebase. I'll try to sketch out a proposal.

**Comment by scolsen** [comment]
I think we should mostly consider this question from the perspective of maintainers/project members/long-term contributors. An unfortunate aspect of our approach is that it's strictly conventional--there's no technical means (that I know of) for us to enforce these practices on Github--so, we'll always have to deal with some number of contributions that don't follow our rules. We can, and should, provide some documentation around our practices to help contributors accord with them, but that's no guarantee that they will. We have to accept that, because the platform/system doesn't provide any mechanisms of enforcement around review practices, outside contributions are and will remain wildcards of a sort. 

That said, I like sticking with the operational capabilities of the platform as much as we can, since this keeps things simple. Maintaining some additional set of conventions on top of the base capabilities of Github increases the intellectual demands of contributing to the project. Unfortunately, Github's approach to reviews tends to lead to massive PRs :/

I'm wondering if the best angle is to stick with the platform's capabilities and alter our reviewing practices to fit, rather than alter our contribution practices. I think tackling big PRs commit by commit is a good idea to help break up the work entailed in a review. I don't see any huge issues arising with the basic strategy of opening *one* new branch per feature request, starting a PR as a draft against that branch early, then reviewing it commit by commit and as it progresses. Finally, when it's ready, mark it ready for review, reviewers can give it one last look through and merge.

Tackling a PR commit by commit is effectively the same as tackling smaller, stacked PRs, only without the additional overhead of having to maintain changes across multiple branches. I know there's a gut reaction to :roll_eyes: when hit with a massive 15+ commit review, but I'm skeptical that there's actually any greater magnitude of work involved in reviewing everything in one place instead of reviewing multiple PRs, so long as the commits make sense and are relatively clean. I think we'll have an easier time working with the assumption that people that use this site can *typically* create logically bounded, and thus digestible, commits, than the assumption that they'll learn and stick to a conventional workflow that requires more complex management of changes.

If we're worried about forgetting which commits we've already reviewed in a big PR (since we might come back to them over a couple days depending on the amount of work involved), we can leave comments on the review referencing the commit eg. `commit <hash> looks good!` that way we know we've already accounted for that piece.

All that said, I'm comfortable enough with git that I'm fine with adopting a more technical approach using git's features or stacked PRs for maintainers--I just think we need to keep in mind that outside contributors won't want to do the extra work of learning a set of conventions just to contribute.

**Comment by gino-m** [comment]
@scolsen, you pretty much nailed why I was thinking of commits as a unit of review; ideally we'd like as little manual intervention and special knowledge on the part of the contributor, both to make it easier to contribute, and to minimize work for maintainers.

@navinsivakumar I'm curious to see what you had in mind. Does it still involve creating multiple PRs? I think rebasing is scary because when done improperly it becomes a big headache to fix, but please cmiiw.

While Navin explores rebase, perhaps we can try a PR or two using commits as a proxy for reviews? I have some changes to submit that I can do that way.

**Comment by scolsen** [comment]
Yeah! Let's give it a shot.

**Comment by valloskut** [comment]
Hi @gino-m, just FYI.  Found this when was looking for ways to control stacked PRs merging. 
https://probot.github.io/apps/dep/

**Comment by gino-m** [comment]
Hey, thanks! At first glance it looks like it prevents merging when there are dependent PRs, but doesn't help showing incremental diffs across stacked PRs? Please cmiiw.

**Comment by valloskut** [comment]
Yes, I believe it only prevents merging.
Not sure if I got you right, but GitHub allows to change base branch of the
PR. So if next stacked PR is based on previous one, it will show the
required diff. The only issue is to merge them in correct order later. Here
is that 'dep' like app can help.

**Comment by gino-m** [comment]
The issue we ran into is that to allow dependent PRs to be set as a base, subsequent stacked PRs all need to live in the contributor's fork . This means dependent PR review history wouldn't be easily discoverable, and maintainers can't be assigned reviewers (unless they're added as a contributor of the fork).

It's completely possible I'm just misunderstanding how GitHub intends for this to be done (if at all). Suggestions welcome!

**Comment by gino-m** [comment]
Iirc the consensus here was that it's very difficult to stack PRs across forks, and that working on the main repo quickly tends to descend into chaos, so we should avoid stacking PRs. Instead, for complex PRs, we should aim to separate work into small, meaningful commits so that reviewers can view them separately if they wish. Closing this issue for now!
